# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecureTravel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecureTravel
pod 'MBBlinkIDUI'
pod 'Onboard'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire'
pod 'WSTagsField'


end
